import { Manrope } from 'next/font/google';

import { cn } from '@/shared/lib/utils';
import '../styles/globals.css';
import Providers from './providers';

const manrope = Manrope({ weight: ['400', '500', '600', '700', '800'], subsets: ['latin'] });

export const metadata = {
  title: 'BalinkBayan CMS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(manrope.className, 'h-full')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
